# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
 
  config.vm.box = "azure"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 80, host: 80

  
  config.vm.provider :azure do |azure, override|
		azure.mgmt_certificate = File.expand_path("azure.pem")
		azure.mgmt_endpoint    = "https://management.core.windows.net"
		azure.subscription_id = ENV['id_azure']
		azure.vm_name     = "pdeportivasbot"
		azure.cloud_service_name = 'pdeportivasbot'
		azure.vm_image    = "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2-LTS-amd64-server-20150506-en-us-30GB"
		azure.vm_size     = "Small"
		config.vm.box_url = "https://github.com/msopentech/vagrant-azure/raw/master/dummy.box"
  		azure.vm_user = "ruben" # defaults to 'vagrant' if not provided
		azure.vm_password = ENV['clave']
		azure.vm_location = "Central US" # e.g., West US
		azure.tcp_endpoints = '80:80'
		azure.ssh_port = "22"
	end

	config.ssh.username = ENV['usuario_ssh']
  	config.ssh.password = ENV['clave']
  	
	config.vm.provision "ansible" do |ansible|
		ansible.sudo = true    	
		ansible.raw_arguments=["-vvvv"]	
		ansible.playbook = "configuracion_ansible.yml"	
		ansible.verbose = "v"
		ansible.host_key_checking = false
	end
 end
